apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec: 
   containers:
     - name: result-app
       image: dockerexemples/votingapp_result:v1
       ports:
         - containerPort: 80